name: minimal-streamlit-example
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python
- conda
- pandas
- numpy
- matplotlib
- pip
- pylint
- pydocstyle
- prophet
- flake8
- black
- hvplot
- bokeh
- holoviews
- pip:
  - streamlit
